### PR TITLE
Enable multiline chat (& other chat improvements)

### LINKED ISSUE #98: Enable multi-line support on chat messages
**Motivation**
Right now, since we just use UILabels for chat messages, our messages only support single lines of text. We want to extend that to support multiple lines of text because that is standard behavior across messaging apps.

**The Task**
Accepting multiline input involves several things:
1. The textbox where the user types in the message would need to be able to dynamically grow and shrink based on the amount of text the user types in or deletes.
2. The size of the textbox displaying the message would be dynamic too based on the number of lines needed to display it.
3. The dynamic size of the tetxbox displaying the message adds some complication to the UITableView calculations for the Table View that is displaying the messages. These need to be handled.

**Requirements**
* Since this is such a common problem, there are bound to be tutorials on how to do this properly online. Look them up and figure out how to apply their solutions to our codebase.
* Also, check out our [contribution guide](https://github.com/ucladevx/Bruin-Bite-iOS/wiki/Contribution-Guide) for the git/github workflow we will be adopting from now.

**Acceptable Criteria**
* Dynamically adjust size (both growing and shrinking) as the size of the message changes. The input text field should get larger and smaller (can cap that at 2 lines for now if turns out to be hard)
* Correct number of lines should be shown when you send or receive a message
* Let’s cap the maximum word size at 300 (do not allow typing post that)
 * Let’s do the line height first, followed by width.

### PR DESCRIPTION
**Pull request by pluscubed**
Resolves #98.

Multi-line chat bubbles and input are both working. Tested on iPhone 8 and iPhone XR simulator. 

Technical changes made: allow multi-line chat UILabels, change constraints to depend on table cell boundaries, change UITextField to UITextView for multi-line input (with a grey border using a UIView extension configurable in Storyboard), move table/input into a StackView for expandable input and easier keyboard constraint animation

The only new issue is that the placeholder text is gone, due to using UITextView instead of UITextField. There are workarounds, but IMO it looks fine (and it's the default look in Messages anyway).

simulator screen shot - iphone xr - 2019-03-03 at 18 46 46

### CODE REVIEW

**Comment by pluscubed** [comment]
Fixed 2 existing issues:
- Pressing the ">" button dismisses the keyboard and doesn't send the message
- Navigation bar becomes black when pressing back in chat

**Comment by pluscubed** [comment]
Fixed 1 more existing issue: 
- Pressing return on sw keyboard does nothing

**Comment by pluscubed** [comment]
Fixed a new issue due to multiline UILabels not playing well with insets.

Also set the chat screen's navbar title to the other person's first name.

**Comment by kamalca** [comment]
Looks good!

**Pull request merged**
