### PR TITLE
Redid login/sign-up UI and navigation

### LINKED ISSUE #96: Redo the Login/Signup UI code
**Motivation**
Right now, the UI for the login is extremely buggy and not user-friendly or developer friendly. It doesn't use a Navigation Controller (which it absolutely should), does labels/buttons all wrong and basically has a lot of things going against it and makes for an overall buggy experience.

**The Task**
Redo the entire UI flow for the login/signup - keeping basic iOS development principles in mind. Follow the designs on our [Zeplin](https://zpl.io/V0ZJ9X9):
* Sign Up/Log In Prompt ([screen 8.30](https://zpl.io/awrDEZN))
* Sign up screen 1 ([screen 8.47](https://zpl.io/b6y7Glm))
* Sign up screen 2 ([screen 8.48](https://zpl.io/agn0RGA)) 
* Sign up screen 3 ([screen 8.49](https://zpl.io/bJKDJP9))
* Log In screen ([screen 8.50](https://zpl.io/VDOZP7g))

You can ignore the action performed by the `Facebook log in button` for now, we will implement that separately. 

All of these new ViewControllers should be placed in a new storyboard called `login.storyboard` and be embedded in a navigation controller such that each screen leads sensibly to the next. Do not worry about linking this new storyboard/nav controller to the main app for now, just create it.

**Some requirements:**
* Design of the VCs should precisely match the designs on zeplin
* Proper constraints should be in place that are tested across all screen sizes ranging from the iPhone SE to the iPhone XS Max.
* Follow standard practices in terms of segues and navigation controllers and write the segues such that the VC-VC segues are created in storyboard, but are called upon the click of the relevant button in the VC code so that we can pass any data along if needed.
* Please refer to the [contribution-guide](https://github.com/ucladevx/Bruin-Bite-iOS/wiki/Contribution-Guide) for a quick primer of our git workflow.
* Each input field should have an associated error message label that is hidden at the beginning of the view's lifecycle and can be made visible programmatically. Get creative about the programmatic interface you design for these error labels (so that the person who is writing the network calls has an easy time populating these and making these visible with error messages from the server)

**Acceptable criteria**:
* A new storyboard `login.storyboard` that meets all of the above requirements and implements the designs from zeplin.

Please ask clarifying questions in this issue thread!

### PR DESCRIPTION
**Pull request by cliffdawg**
Fixes #96 

I redid the auto-layout and constraints for the login/sign-up controllers, and tested them out on multiple iPhone simulation sizes. The layout is now primarily based around horizontal and vertical center constraints.

I embedded the login/sign-up flow into a Navigation Controller, and transferred all the top elements into the navigation bar. I implemented the required segues through `override func prepare(for segue: UIStoryboardSegue, sender: Any?) { }` in each ViewController file.

I created a Utilities file for reusable helper functions such as `func displayErrorLabel(text: String, field: UIView)` and `func formatNavigation(controller: UINavigationController)`
The displayErrorLabel function animates an error message with a given text above a given view passed in through the parameters. Call it from the static instance of the Utilities object to use it anywhere in the project.
The formatNavigation function sets up the navigation bar with the specified color, font, size, and icons in the Zeplin files.

Additionally, I installed the ViewAnimator pod to make animating the error message much easier.

I added a file called ClearBackButton to the Assets folder. The purpose this serves is that the default back arrow icon for the navigation bar can't be removed or made transparent, so my solution was to set its image to that of a clear image file, which for all intents and purposes solves the issue.

### CODE REVIEW

**Comment by HirdayGupta** [comment]
@cliffdawg thanks for the pull request! I'm going to get round to reviewing it soon, in the meanwhile, can you post screenshots of the new screens (with or without error labels, for any iPhone) just to get some visual documentation of your changes in the PR?

**Comment by HirdayGupta** [comment]
@cliffdawg also, as a general rule, you should add in the "Fixes #__" at the top of your PR description to indicate to Github which issue to close when this PR is merged.

**Comment by cliffdawg** [comment]
Here are the screenshots.
https://user-images.githubusercontent.com/18109476/48045147-f25c6500-e143-11e8-86f2-913f1595326f.png
https://user-images.githubusercontent.com/18109476/48045150-f6888280-e143-11e8-91cd-f9fce4ca5f80.png
https://user-images.githubusercontent.com/18109476/48045151-f7211900-e143-11e8-89e5-9bcf7b16d512.png
https://user-images.githubusercontent.com/18109476/48045152-f7211900-e143-11e8-9304-20bcd7c0faeb.png
https://user-images.githubusercontent.com/18109476/48045153-f7211900-e143-11e8-8128-dc81c5e9c527.png

**Review by HirdayGupta — CHANGES_REQUESTED** [review]
Good work so far! A few pending things:
1. [The first screen on the iPhone XR](https://user-images.githubusercontent.com/18088721/48393976-83908600-e6c6-11e8-8baf-929edf66af9a.png) seems to have some constraint issues. Usually indicative of underlying constraint problems. Fix them and tell me how you fixed it (what the issue was and how you solved it).
2. Add basic input validation to your code. For instance - if the `confirm password` and `password` fields don't match - call your error label class and show an appropriate error message. Do this for all input you can validate on-device (essentially everything except email).
3. I'll be giving you a more detailed code review soon - but I thought it was important that you knew the big features missing before that so you could get started on that.

**Comment by HirdayGupta** [comment]
Merged into `networking-rework` #105 and successfully into development in b1e9e16a067f3b3c1788f56b2ddf26800ada7b9a

**Pull request closed without merging**
